version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: newyork1176
      MYSQL_DATABASE: inventory
    volumes:
      - ./DDL.sql:/docker-entrypoint-initdb.d/DDL.sql

  producer:
    build: ./Producer
    ports:
      - "5123:5123"
    environment:
      RABBITMQ_HOST: rabbitmq
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: newyork1176
      MYSQL_DATABASE: inventory
    depends_on:
      - mysql
    command: bash -c "sleep 10 && python producer.py"


  # consumer_one:
  #   build: ./Consumer_one
  #   ports:
  #     - "5124:5124"
  #   environment:
  #     RABBITMQ_HOST: rabbitmq
  #     MYSQL_HOST: mysql
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: ujjwalmk
  #     MYSQL_DATABASE: inventory
  #   depends_on:
  #     - mysql
  #   command: bash -c "sleep 10 && python healthcheck.py"


  consumer_two:
    build: ./Consumer_two
    ports:
      - "5125:5125"
    environment:
      RABBITMQ_HOST: rabbitmq
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: newyork1176
      MYSQL_DATABASE: inventory
    depends_on:
      - mysql
    command: bash -c "sleep 10 && python item_creation.py"

  consumer_three:
    build: ./Consumer_three
    ports:
      - "5126:5126"
    environment:
      RABBITMQ_HOST: rabbitmq
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: newyork1176
      MYSQL_DATABASE: inventory
    depends_on:
      - mysql
    command: bash -c "sleep 10 && python stock_management.py"

  consumer_four:
    build: ./Consumer_four
    ports:
      - "5127:5127"
    environment:
      RABBITMQ_HOST: rabbitmq
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: newyork1176
      MYSQL_DATABASE: inventory
    depends_on:
      - mysql
    command: bash -c "sleep 10 && python order_processing.py"

  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"
      - "15672:15672"


volumes:
  rabbitmq_data:


# # Extra
# version: '3.8'

# services:
#   mysql:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD: ujjwalmk
#       MYSQL_DATABASE: inventory
#     volumes:
#       - ./DDL.sql:/docker-entrypoint-initdb.d/DDL.sql

#   producer:
#     build: ./Producer
#     ports:
#       - "5123:5123"
#     environment:
#       RABBITMQ_HOST: rabbitmq
#       MYSQL_HOST: mysql
#       MYSQL_USER: root
#       MYSQL_PASSWORD: ujjwalmk
#       MYSQL_DATABASE: inventory
#     depends_on:
#       - mysql
#       - rabbitmq
#     command: bash -c "sleep 10 && python producer.py"

#   consumer_one:
#     build: ./Consumer_one
#     ports:
#       - "5124:5124"
#     environment:
#       RABBITMQ_HOST: rabbitmq
#       MYSQL_HOST: mysql
#       MYSQL_USER: root
#       MYSQL_PASSWORD: ujjwalmk
#       MYSQL_DATABASE: inventory
#     depends_on:
#       - mysql
#       - rabbitmq
#       - producer
#     healthcheck:
#       test: ["CMD-SHELL", "python healthcheck.py"]
#       interval: 10s
#       retries: 5
#     command: bash -c "sleep 10 && python healthcheck.py"

#   consumer_two:
#     build: ./Consumer_two
#     ports:
#       - "5125:5125"
#     environment:
#       RABBITMQ_HOST: rabbitmq
#       MYSQL_HOST: mysql
#       MYSQL_USER: root
#       MYSQL_PASSWORD: ujjwalmk
#       MYSQL_DATABASE: inventory
#     depends_on:
#       - mysql
#       - rabbitmq
#       - producer
#       - consumer_one
#     command: bash -c "sleep 10 && python item_creation.py"

#   consumer_three:
#     build: ./Consumer_three
#     ports:
#       - "5126:5126"
#     environment:
#       RABBITMQ_HOST: rabbitmq
#       MYSQL_HOST: mysql
#       MYSQL_USER: root
#       MYSQL_PASSWORD: ujjwalmk
#       MYSQL_DATABASE: inventory
#     depends_on:
#       - mysql
#       - rabbitmq
#       - producer
#       - consumer_one
#     command: bash -c "sleep 10 && python stock_management.py"

#   consumer_four:
#     build: ./Consumer_four
#     ports:
#       - "5127:5127"
#     environment:
#       RABBITMQ_HOST: rabbitmq
#       MYSQL_HOST: mysql
#       MYSQL_USER: root
#       MYSQL_PASSWORD: ujjwalmk
#       MYSQL_DATABASE: inventory
#     depends_on:
#       - mysql
#       - rabbitmq
#       - producer
#       - consumer_one
#     command: bash -c "sleep 10 && python order_processing.py"

#   rabbitmq:
#     image: rabbitmq:3.8-management
#     ports:
#       - "5672:5672"
#       - "15672:15672"
#     healthcheck:
#       test: ["CMD", "rabbitmqctl", "status"]
#       interval: 10s
#       retries: 5
#       timeout: 5s
