version: '3.8'

services:
  producer:
    build: ./Producer
    ports:
      - "5000:5000"
    environment:
      RABBITMQ_HOST: rabbitmq

  consumer_one:
    build: ./Consumer_one
    ports:
      - "5001:5001"
    environment:
      RABBITMQ_HOST: rabbitmq

  consumer_two:
    build: ./Consumer_two
    ports:
      - "5002:5002"
    environment:
      RABBITMQ_HOST: rabbitmq

  consumer_three:
    build: ./Consumer_three
    ports:
      - "5003:5003"
    environment:
      RABBITMQ_HOST: rabbitmq

  consumer_four:
    build: ./Consumer_four
    ports:
      - "5004:5004"
    environment:
      RABBITMQ_HOST: rabbitmq

  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  rabbitmq_data:
