# version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: newyork1176
      MYSQL_DATABASE: inventory
    volumes:
      - ./DDL.sql:/docker-entrypoint-initdb.d/DDL.sql

  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
    # command: ["bash", "-c", "/bin/bash /app/delay_startup.sh && sleep 1 && rabbitmq-server"]
    # volumes:
    #   - "./delay_startup.sh:/app/delay_startup.sh"

  flask:
    build: ./flask
    ports:
      - "5001:5001"
    depends_on:
      - consumer_one
      - consumer_two
      - consumer_three
      - consumer_four
    command: python -u app.py

  producer:
    build: ./Producer
    ports:
      - "5123:5123"
    environment:
      RABBITMQ_HOST: rabbitmq
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: newyork1176
      MYSQL_DATABASE: inventory
    depends_on:
      - consumer_one
      - mysql
    command: bash -c "sleep 20 && python producer.py"


  consumer_one:
    build: ./Consumer_one
    ports:
      - "5124:5124"
    environment:
      RABBITMQ_HOST: rabbitmq
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: ujjwalmk
      MYSQL_DATABASE: inventory
    depends_on:
      - mysql
    # entrypoint: ./entrypoint.sh
    command: bash -c "sleep 10 && python healthcheck.py"


  consumer_two:
    build: ./Consumer_two
    ports:
      - "5125:5125"
    environment:
      RABBITMQ_HOST: rabbitmq
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: newyork1176
      MYSQL_DATABASE: inventory
    depends_on:
      - consumer_one
      - mysql
    command: bash -c "sleep 30 && python item_creation.py"

  consumer_three:
    build: ./Consumer_three
    ports:
      - "5126:5126"
    environment:
      RABBITMQ_HOST: rabbitmq
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: newyork1176
      MYSQL_DATABASE: inventory
    depends_on:
      - consumer_one
      - mysql
    command: bash -c "sleep 30 && python stock_management.py"

  consumer_four:
    build: ./Consumer_four
    ports:
      - "5127:5127"
    environment:
      RABBITMQ_HOST: rabbitmq
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: newyork1176
      MYSQL_DATABASE: inventory
    depends_on:
      - consumer_one
      - mysql
    command: bash -c "sleep 30 && python order_processing.py"